In [14]:
! python --version

Python 3.12.4


In [15]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # Should return True if CUDA is available


2.5.1+cpu
False


In [17]:
tensor_a = torch.Tensor(1)
tensor_a, tensor_a.dtype, tensor_a.ndim, tensor_a.shape, tensor_a.item()

(tensor([1.]), torch.float32, 1, torch.Size([1]), 1.0)

In [18]:
tensor = torch.Tensor([1 , 2, 3])
tensor, tensor.dtype, tensor.ndim, tensor.shape

(tensor([1., 2., 3.]), torch.float32, 1, torch.Size([3]))

In [24]:
matrix = torch.Tensor([[1, 2, 3], [4, 5, 6]])
matrix, matrix.dtype, matrix.ndim, matrix.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 torch.float32,
 2,
 torch.Size([2, 3]))

Create random tensor

In [25]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(tensor([[0.3157, 0.5548, 0.4055, 0.1608],
         [0.5565, 0.2924, 0.4538, 0.4430],
         [0.8348, 0.1451, 0.4072, 0.0061]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [26]:
#zeros
zeros = torch.zeros(size=(3, 4, 4))
zeros, zeros.dtype, zeros.ndim, zeros.shape


(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.float32,
 3,
 torch.Size([3, 4, 4]))

In [28]:
#ones
ones = torch.ones(size=(3, 4, 4))
ones, ones.dtype, ones.ndim, ones.shape

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.float32,
 3,
 torch.Size([3, 4, 4]))

In [29]:
# arange
arange = torch.arange(start=1, end=10, step=2)
arange, arange.dtype, arange.ndim, arange.shape

(tensor([1, 3, 5, 7, 9]), torch.int64, 1, torch.Size([5]))

In [31]:
tensor = torch.tensor(data = [1, 2, 3],
                      dtype = torch.float32,
                      device = 'cpu',
                      requires_grad = True)
tensor, tensor.dtype, tensor.ndim, tensor.shape, tensor.device

(tensor([1., 2., 3.], requires_grad=True),
 torch.float32,
 1,
 torch.Size([3]),
 device(type='cpu'))

# tensor operations

In [32]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [33]:
x = x+10
x

tensor([11, 12, 13])

In [34]:
x= x -2
x

tensor([ 9, 10, 11])

In [35]:
x = x*2
x   

tensor([18, 20, 22])

In [36]:
x = x/2
x

tensor([ 9., 10., 11.])

In [37]:
x = x*x
x

tensor([ 81., 100., 121.])

In [ ]:
x = torch.multiply(x, x)   # x = x**2  element wise multiplication
x

tensor([ 6561., 10000., 14641.])

In [ ]:
x = torch.matmul(x, x)      #matrix multiplication
x

tensor(3.5741e+08)

In [40]:
# manual seed generation
torch.manual_seed(42)
random_tensor = torch.rand(size=(3, 4))
random_tensor   

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])